name: Deploy GitHub Page

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.9"
  NODE_VERSION: "18"

jobs:
  notebooks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: converter
    steps:
      - name: Checkout website-binder repository
        uses: actions/checkout@v3
        with:
          repository: LucienZhang/website-binder
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Convert notebooks to HTML
        run: python main.py
      - name: Update notebooks artifacts
        uses: actions/upload-artifact@v3
        with:
          name: notebooks
          path: converter/static
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - run: npm ci
      - run: npm run build
      - name: Update notebooks artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs/.vuepress/dist
  deploy:
    needs: [notebooks, docs]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download docs artifact
        uses: actions/download-artifact@v3
        with:
          name: docs
          path: docs
      - name: Download notebooks aritifact
        uses: actions/download-artifact@v3
        with:
          name: notebooks
          path: notebooks
      - run: ls -R docs
      - run: ls -R notebooks
      # - name: Deploy to GitHub Pages
      #   uses: crazy-max/ghaction-github-pages@v3
      #   with:
      #     target_branch: gh-pages
      #     build_dir: docs
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
